### ISSUE TITLE
remove item/index feature

### ISSUE THREAD

**Issue by jd1378** [donmccurdy/circular-array#1]
Hi
Can you add a remove item/index method ?

**Comment by donmccurdy** [comment]
This package represents a fixed-length array, so at most you could overwrite a particular index with null or undefined. I could be open to suggestions for new methods if they:

(1) Match existing JS array APIs where possible.
(2) Maintain a fixed-length underlying array.
(3) Run in constant time.

To me "remove" implies shortening the array, which wouldn't be supported here. But overwriting a particular (relative) index, or rotating the circular array back one step, perhaps?

**Comment by jd1378** [comment]
Well , I don't exactly remember what I wanted back in 26 days , but I think I wanted something like this:
```
gizmos.push(gizmo1); //   [gizmo1]
gizmos.push(gizmo2); //   [gizmo1, gizmo2]
gizmos.push(gizmo3); //   [gizmo1, gizmo2, gizmo3]
gizmos.removeIndex(2); //   [gizmo1, gizmo3]
gizmos.push(gizmo4); //   [gizmo1, gizmo2, gizmo4]
```
I hope its clear now :)

**Comment by donmccurdy** [comment]
So one issue is that this means an O(n) change to the array, moving everything after the removed index back, or creating a new array. I'd like to keep this project limited to O(1) methods, where changes happen in place. You might be better off using a native array and methods like array.slice/splice for that.
